### ISSUE TITLE
Authentication issues with PCF

### ISSUE THREAD

**Issue by viniciusccarvalho** [cf-platform-eng/cf-containers-broker#12]
When deploying with BOSH:

Ferdy, the manage link is not working. One thing I noticed is that the manifest refers to it to cf-containers-broker.<root_domain>, but I could not find a job step that actually creates a route on PCF. 

So this ends on the route never being found. I tried to replace it by the broker ip (and that's how I registered it), but after being challenged by PCF (1.2.0) auth screen, it redirects back to the console application. I can't reach the manage endpoint.

I guess I could break this into two "mini issues"

- Auth issues
- How to register the broker application with cf

Regards

**Comment by frodenas** [comment]
Added some comments about how the route is registered at https://github.com/cf-platform-eng/cf-containers-broker/commit/59b666b55629cdbd6a04a15394c820cd8a9c2a89.
