### ISSUE TITLE
Syslog Drain tcp instead of http

### ISSUE THREAD

**Issue by tyyko** [cf-platform-eng/cf-containers-broker#15]
I think you should use by default syslog (tcp) protocol instead of http, also because with your example with logsearch, the default settings listen for tcp connections, to use http you have to search for a plugin.

```file: cf-containers-broker/app/models/docker_manager.rb LINE 116```
``` 'syslog' instead of 'http' ```

It would be even better to allow changes using some settings file instead of re-building the image

Edit: even because http does not exist:
```  ERR SinkManager: Invalid syslog drain URL (http://xxxxx) for application xxxxxx. Err: Invalid scheme type http, must be https, syslog-tls or syslog ```

**Comment by frodenas** [comment]
When I wrote the broker the only supported method in CF for the draining url was `http`. Now, CF is using loggregator to sink the log messages, and it allows to configure the transport method (and removed the http support btw).

So, yes, the broker must be updated to support (and make configurable) the new transport methods. Unfortunately, I don't have bandwidth to update it in the next months, so any contributions will be very welcomed.

**Comment by tyyko** [comment]
Sadly I have no time too, even because my use of docker containers is just a workaround to get my main project working while waiting for new features of Diego.. anyway, I just suggest you to edit the file ``` cf-containers-broker/app/models/docker_manager.rb LINE 116 ``` with ```syslog``` instead of ```http``` this would make it working by default using tcp protocol which is the default input for many log ingestors, like logstash.

**Comment by frodenas** [comment]
@tyykp I'm going to reopen this issue until I fix it.

**Comment by frodenas** [comment]
Fixed at https://github.com/cf-platform-eng/cf-containers-broker/commit/30cc34858fccb0433644d1a50e37ac0ff1e9ac41.
