### ISSUE TITLE
Got authentication error when accessing the dashboard 

### ISSUE THREAD

**Issue by datianshi** [cf-platform-eng/cf-containers-broker#23]
Hi @frodenas Do you have any idea what uaa authentication scope to access the dashboard?

**Comment by frodenas** [comment]
You should have an `cc-service-dashboards` uaa client with the permissions documented here: http://docs.cloudfoundry.org/services/dashboard-sso.html#enabling-the-feature-in-cloudfoundry

**Comment by datianshi** [comment]
Thanks @frodenas 

Did it looked at uaa log
Got
"error="invalid_grant", error_description="A redirect_uri can only be used by implicit or authorization_code grant types."

Not sure if that is new to the cf release (I am using 211)

**Comment by frodenas** [comment]
Hmm, not sure if anything changed at the latest releases, I'll try to reproduce this on a fresh install this week.

**Comment by datianshi** [comment]
I misunderstood how the dashboard sso works.
I thought I need to inject the dashboard client id and secret to replace cc-service-dashboards.
Turned out that cc-service-dashboards is used by cloud controller. when cf create-service-broker, cloud controller auto register dashboard client secret into uaa. 

So this is not an issue. Thank you
