### ISSUE TITLE
Passing credentials to a container

### ISSUE THREAD

**Issue by dhcole** [cf-platform-eng/cf-containers-broker#24]
Wondering if someone might have ideas on how to deal with this scenario: I have a docker image that does a task but that needs credentials to write the output of that task to a shared resource, such as S3. I'd like to run that task as a container service from an application on CloudFroundry. So the application would issue a POST request to [/v2/service_instances](https://apidocs.cloudfoundry.org/215/service_instances/creating_a_service_instance.html) to create the service, it would run its process, and output the result to S3, and terminate. The benefit to this is the process would run in an isolated container instead of on the application.

I don't know how to pass the credentials and some other configuration from the application to the service. I was thinking the `parameters` attribute in the request body might allow for this, but I'm not sure how the service would use that data. Ideally it could be read through `env` variables.

Would love any thoughts on how this could work. Thanks.

**Comment by frodenas** [comment]
If the S3 credentials are fixed for all applications, the easy way is to statically populate them at deploy time using the `environment` property of the container definition (see [CONTAINERS.md](https://github.com/cf-platform-eng/cf-containers-broker/blob/master/DOCKER.md#properties-format)). An example would be:

```yaml
container:
  backend: 'docker'
  image: 'frodenas/postgresql'
  tag: 'latest'
  environment:
    - "AWS_ACCESS_KEY_ID=XXX"
    - "AWS_SECRET_ACCESS_KEY=XXX"
```

But I guess what you're looking for is to allow each application to provision and/or bind the service passing their own credentials. If this is the case, the [Service Broker API v2.6](http://docs.cloudfoundry.org/services/api.html#provisioning) allows to pass some arbitrary provision parameters. Unfortunately, this broker does not accept yet arbitrary parameters. If you confirm me this is the use case you're looking for then I can update the broker to accept those parameters. The way it will work will be pretty simple, it will inject those parameters into the container using environment variables. An example api request with arbitrary parameters:

```json
{
  "organization_guid": "org-guid-here",
  "plan_id":           "plan-guid-here",
  "service_id":        "service-guid-here",
  "space_guid":        "space-guid-here",
  "parameters":        {
    "parameter1": 1,
    "parameter2": "value"
  }
}
```

will be injected into the container as these environment variables:

```
PARAMETER1="1"
PARAMETER2="VALUE"
```

Let me know if this will work for you.

**Comment by dhcole** [comment]
Hi @frodenas, thanks for this. That case is exactly what we're looking for. For us, the parameters are dynamic so setting them in the request and having them available as environment variables in the container solve this issue.

**Comment by frodenas** [comment]
@dhcole I've just added support for [service arbitrary parameters](https://github.com/cf-platform-eng/cf-containers-broker/commit/4925d7391a409fd8eb20ef5c5005e2c50221e8b9). If you are using the [Docker BOSH release](https://github.com/cf-platform-eng/docker-boshrelease), update it to [version 16](http://bosh.io/releases/github.com/cf-platform-eng/docker-boshrelease?version=16), as it includes the latest cf-containers-broker code.

**Comment by dhcole** [comment]
This is really great. Thanks so much for the quick response and updating the broker to support this.
