### ISSUE TITLE
Can't create Service Keys

### ISSUE THREAD

**Issue by jgerbszt** [cf-platform-eng/cf-containers-broker#26]
App_guid parameter in binding request is no longer mandatory from SB API v2.5:
https://docs.cloudfoundry.org/services/api-v2.5.html#binding

Well, there's an asterisk by the name of the field, but the comment tells that it won't appear when user creates Service Keys. This is the minor issue in documentation, but the bigger one is in containers broker code. Take a look at this line:
https://github.com/cf-platform-eng/cf-containers-broker/blob/master/app/controllers/v2/service_bindings_controller.rb#L9

The 'fetch' method validates that 'app_guid' param value exists and the request ends up with 400 status code. You can see it when you issue 'cf create-service-key myservice mykey'.

I would suggest to remove the line of code linked above. First, we'll be able to create keys for services, second - app_guid variable is not used at all anyway.

**Comment by frodenas** [comment]
Love these backwards incompatible changes :sob: I see also this field is [no longer guaranteed](https://docs.cloudfoundry.org/services/api.html#api-changes-since-v2-4) even on service binding requests when using API v2.6.

I'll fix this later this week.

**Comment by frodenas** [comment]
Fixed at https://github.com/cf-platform-eng/cf-containers-broker/commit/fa7ee93dfdf2141bc083dd995e450067dd634636.

If you're using the [Docker BOSH release](https://github.com/cf-platform-eng/docker-boshrelease), you'll need to upgrade to [v17](http://bosh.io/releases/github.com/cf-platform-eng/docker-boshrelease?version=17).
