### ISSUE TITLE
Docker error: port is already allocated on creating service instance 

### ISSUE THREAD

**Issue by amulyas** [cf-platform-eng/cf-containers-broker#27]
time="2015-09-21T20:23:44.368858845Z" level=error msg="Handler for POST /containers/{name:.*}/start returned error: Cannot start container 162bf2517993b7c9a0dda2f521c14d60abfacea0410fe3ba3e7cbf9483b37bf3: Bind for 0.0.0.0:32898 failed: port is already allocated" 

Full Error 
==> /var/vcap/sys/log/docker/docker.stderr.log <==
time="2015-09-21T20:23:44.230560556Z" level=info msg="POST /v1.16/containers/162bf2517993b7c9a0dda2f521c14d60abfacea0410fe3ba3e7cbf9483b37bf3/start" 
time="2015-09-21T20:23:44.262932660Z" level=warning msg="Failed to allocate and map port 32898: Bind for 0.0.0.0:32898 failed: port is already allocated" 
time="2015-09-21T20:23:44.368858845Z" level=error msg="Handler for POST /containers/{name:.*}/start returned error: Cannot start container 162bf2517993b7c9a0dda2f521c14d60abfacea0410fe3ba3e7cbf9483b37bf3: Bind for 0.0.0.0:32898 failed: port is already allocated" 
time="2015-09-21T20:23:44.369028791Z" level=error msg="HTTP Error" err="Cannot start container 162bf2517993b7c9a0dda2f521c14d60abfacea0410fe3ba3e7cbf9483b37bf3: Bind for 0.0.0.0:32898 failed: port is already allocated" statusCode=500 
time="2015-09-21T20:23:44.371140377Z" level=info msg="GET /v1.16/containers/162bf2517993b7c9a0dda2f521c14d60abfacea0410fe3ba3e7cbf9483b37bf3/json" 
time="2015-09-21T20:23:44.373804162Z" level=info msg="DELETE /v1.16/containers/162bf2517993b7c9a0dda2f521c14d60abfacea0410fe3ba3e7cbf9483b37bf3?force=true&v=true" 

==> /var/vcap/sys/log/cf-containers-broker/cf-containers-broker.log <==
I, [2015-09-21T20:23:44.474298 #7511]  INFO -- : #<Exceptions::BackendError: Cannot start Docker container `cf-5edc4f2a-fe06-4d4a-bf2c-64160bdaae2a'>
I, [2015-09-21T20:23:44.474549 #7511]  INFO -- : /var/vcap/data/packages/cf-containers-broker/cf3a65fcc5d23a958fcc98dcfa61b9cc0070aa99.1-511a4ef372c7725e9347426de45b3d7baec200f8/app/models/docker_manager.rb:77:in `create'
/var/vcap/data/packages/cf-containers-broker/cf3a65fcc5d23a958fcc98dcfa61b9cc0070aa99.1-511a4ef372c7725e9347426de45b3d7baec200f8/app/controllers/v2/service_instances_controller.rb:22:in `update'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:198:in `process_action'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:10:in `process_action'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:19:in `process_action'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:137:in `process'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:30:in `process'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:196:in `dispatch'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:237:in `block in action'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:45:in `serve'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `each'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `serve'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:84:in `run_callbacks'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:38:in `call_app'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `block in call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:26:in `tagged'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `tagged'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/static.rb:116:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/railties-4.2.3/lib/rails/application.rb:165:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:580:in `process_client'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:674:in `worker_loop'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529:in `spawn_missing_workers'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:140:in `start'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/bin/unicorn:23:in `load'
/var/vcap/packages/cf-containers-broker/vendor/bundle/ruby/2.1.0/bin/unicorn:23:in `<main>'
I, [2015-09-21T20:23:44.474901 #7511]  INFO -- :   Response: {"headers":{"X-Frame-Options":"SAMEORIGIN","X-XSS-Protection":"1; mode=block","X-Content-Type-Options":"nosniff"},"body":"{\"description\":\"#<Exceptions::BackendError: Cannot start Docker container `cf-5edc4f2a-fe06-4d4a-bf2c-64160bdaae2a'>\"}"}
I, [2015-09-21T20:23:44.475020 #7511]  INFO -- : Completed 500 Internal Server Error in 552ms (Views: 0.1ms)

**Comment by frodenas** [comment]
Who has the 32898 port allocated? Is there any other service running on the host beside Docker and the broker?

The broker assumes that there aren't any other service allocating ports, so it guesses the next available port inspecting the docker daemon. If there're any other services allocating ports, then set the `allocate_docker_host_ports` property to false, so the Docker daemon will retry on next available ports.

**Comment by amulyas** [comment]
@frodenas there is no other service running on host expect docker and broker .. it used by docker only 

4adb795cc721        lnguyen/logstash:1.4    "/scripts/run.sh "   6 days ago          Up 4 days           0.0.0.0:32890->514/tcp, 0.0.0.0:32897->9200/tcp, 0.0.0.0:32898->9300/tcp                            cf-b58d1592-66c3-490c-b17f-975fe7d9777d

**Comment by frodenas** [comment]
Would you ming send me the output of  `docker inspect 4adb795cc721`?

Also, have you started the previous container using the broker or manually?

**Comment by amulyas** [comment]
thanks @frodenas  here it is   https://gist.github.com/amulyas/31fdc2ee6b57c33f962d
all the dockers container are started by broker no manual docker images ..

**Comment by frodenas** [comment]
Thanks @amulyas. Let me take a look because I believe there's a bug at the broker when it looks up for the already allocated ports.

**Comment by amulyas** [comment]
@frodenas thank you very much for looking into this we use this broker with two docker based services and have issues in both .. let me know if there is anything I can do to help you fix it ..

**Comment by frodenas** [comment]
@amulyas I'm unable to reproduce your problem. Can you give me more details about how you've deployed this service broker? Using the [Docker BOSH release](https://github.com/cf-platform-eng/docker-boshrelease)?

**Comment by amulyas** [comment]
@frodenas yes using docker bosh release you mentioned.. the reason why you may be unable to reproduce it because you need try few create then delete then create and so on ..

**Comment by frodenas** [comment]
@amulyas Thanks, I was able to reproduce the problem. I'll fix this ASAP.

**Comment by vlerenc** [comment]
I just migrated to the latest version and ran into the same issue.
Logs of broker and two nodes are available if you need them.
In my case/test scenario, I observed this/this is what roughly happened:

Broker is tasked to create three service instances:
1. Service (mongodb, 4fe5dc0d-ebe5-4dee-bb27-91e0228bd9e8)
32768, 32769 -> ends up on docker/1
2. Service (postgresql, e75fb764-1f14-48e1-971c-cacfbde788fd)
32770 -> ends up on docker/0
3. Service (rabbitmq, a86e17d3-b5c7-4612-8e5e-1996eca060d5)
32770, 32771 -> ends up on docker/0 and causes:
BackendError: Cannot start Docker container `cf-a86e17d3-b5c7-4612-8e5e-1996eca060d5' (app/models/docker_manager.rb:77:in `create'…)
Completed 500 Internal Server Error

In docker/0 I see:
POST /v1.16/containers/f7e090a673768399bbb7b741358c16bf01386c94d5c9da508ec4fdf5744b0f29/start
-> Failed to allocate and map port 32770: Bind for 0.0.0.0:32770 failed: port is already allocated
-> Handler for POST /containers/{name:.*}/start returned error: Cannot start container statusCode=500

I hope this helps, but I read you could already reproduce the issue.

I guess, in the meanwhile I can switch to broker.allocate_docker_host_ports=false to get the old behavior back?

**Comment by frodenas** [comment]
I've identified the issue and I'm working on a fix right now.

**Comment by vlerenc** [comment]
@frodenas, as expected, broker.allocate_docker_host_ports=false works fine, so I'll switch to this setting until you make a fix available. Thanks in advance, Vedran

**Comment by amulyas** [comment]
@frodenas thank you very much for looking into this and planning to fix it .. its amazing ...
we will be using this broker later this week in our product launch .. I will wait for your fix and as soon as you have it ready I can implement it on our container broker .. thank you very much again for helping us out

**Comment by frodenas** [comment]
@amulyas @vlerenc I pushed a temporary (and not optimal) fix that basically consists of reducing the default number of unicorn workers to 1. The fix has been introduced in [Docker BOSH release v19](http://bosh.io/releases/github.com/cf-platform-eng/docker-boshrelease?version=19), although you can use whatever version you want (ie v18) as far as you add this property to your deployment manifest: `broker.unicorn.worker_processes:  1`. I know this is not the best solution, but will solve the problem you've been experiencing. 

The problem resides in the [DockerHostPortAllocator](https://github.com/cf-platform-eng/cf-containers-broker/blob/master/lib/docker_host_port_allocator.rb) Singleton when using multiple unicorn workers. Each worker will fork the application when it is started, and even if the singleton is loaded at the app initializators, all modifications to the allocated ports instance variable will land on a different physical memory (using copy-on-write), so there is NOT a shared memory between workers. That means that one worker reserving some ports are not visible to the other workers.

The final solution might be a bit tricky, so I'm asking for your thoughts. I see 3 alternatives (happy to hear if you can think on another approaches):

1) Make this fix permanent by disabling the number of workers configuration (always set to 1). The advantage is that no complex work is involved, the disadvantage is that potentially reduces the number of concurrent requests to the broker.

2) Every time a new container is started, check with the Docker daemon what ports have been allocated. This has the advantage that we don't need to share any state between workers, but might have the disadvantage of costly queries to the docker daemon when there're lots of docker containers running (ie, on a swarm deployment) and also that we can eventually experience port conflicts as we cannot control the query's concurrency to the docker daemon (2 workers simultaneously querying the docker daemon will end allocating the same ports).

3) Introduce some shared state between workers. This might  be quite simple, as the state can be stored in a file (I'd prefer to not introduce a dependency like a DB or memcached). The advantage is that we'll have a shared store between workers and we can control the access concurrency, so we can guarantee that there are no port conflicts. The disadvantage is that we're introducing some "state".

Thoughts?

**Comment by amulyas** [comment]
thank you very much @frodenas we are using docker/15 release will this flag works there too or just from 18 and later

**Comment by frodenas** [comment]
@amulyas Yes, the property will also work for v15.

**Comment by vlerenc** [comment]
@frodenas From the options above, I would probably go with #1 or #3 as #2 is unsafe.

However, I would like to throw in the points from https://github.com/cf-platform-eng/cf-containers-broker/issues/17#issuecomment-123605179 which are basically robustness (the broker misses ports of temporary unavailable Docker nodes during initialization) and scale-out limitations (each port gets used only once, independent of the Docker node). 

In that regard, have you known of https://github.com/docker/swarm/tree/master/scheduler/filter#port-filter? You can launch Swarm with a filter option and if you do so with the port filter, Swarm will try to find a Docker node that has free ports. Only if it cannot find a node with free ports, the container start will fail.

The biggest advantage of the port filter: If you go with option #1 or #3, you could "burn/mark" a port as exhausted only when it's exhausted on all nodes. This way the scale-out limitation would be gone. That was what I hoped for in Swarm and it's available now (not sure since when).

Independent of the port filter and the concurrency issue: if you implement a retry on missed port filter constraint/port already allocated, you could also improve robustness against Docker nodes down during broker initialization, but I wouldn't consider this as option #4 for the concurrency issue as it would regularly mean (not only in the corner case of a down Docker node during broker initialization) that you run N (number of workers) Swarm calls before you finally succeed.

One tricky catch is how to handle containers with multiple exposed ports. Not sure how good the error responses are and if you could see from them which port exactly must be "burned/marked in use" throughout all nodes, but it may be worth a try.

**Comment by frodenas** [comment]
@vlerenc Thanks. The port filter, albeit useful, doesn't work when you're not using swarm as a backend :( But you raised a good point about implementing a retry logic.

**Comment by vlerenc** [comment]
@frodenas Well, if you generally rely on retry with multiple workers, they will fail N-1 (N being number of workers) times on each start as every worker has to learn that one of them has used up another port, right?

As for the port filter, yes it's about Swarm when you start it. If it would be added to Swarm (new property) you could resolve the scale-out issue, I believe. If you implement retry and only that for now, you have a way to detect a used port and mitigate by probing the next (independent of whether a single Docker node returned "port in use" or Swarm which does it for all its nodes). So maybe no need to handle both options separately in the containers-broker itself?

**Comment by amulyas** [comment]
@frodenas it working like a charm, thank you very much for fixing it ..appreciate it allot  if you ask me I would choose option 1. As running heavy query will take same time as running with one unicorn process .. as create service, is a less frequent transaction .. then anything else in cloud foundry so number are not that high .. number 3 is again not good as being stateless is one of the great property of this broker .. I guess we may be one of the major consumer of this broker and if it can handle our load with just one unicorn process it should be ok for others too ..

**Comment by amulyas** [comment]
thanks again @frodenas closing this issues now

**Comment by vlerenc** [comment]
Just a comment on limiting the number of workers to 1. That effectively means that all access to the broker is serialized which may lead to unresponsive behavior when using the CF CLI, right? Not sure how much of a problem this is/how much really will happen at the same time. Service creation definitely and maybe it will run sometimes into a timeout.

**Comment by frodenas** [comment]
Correct, reducing the number of workers to 1 would lead to timeouts.

**Comment by drnic** [comment]
Could we move the state in the singleton into a local file?

(My original port allocation code did this; with a lock around the file; perhaps borrow some code from there?)
